### ISSUE TITLE
Make user pin draggable

### ISSUE THREAD

**Issue by omarsawalhah** [jeffreykemp/jk64-plugin-reportmap#109]
Hi Jeff, 
Great Plugin, thanks it helped me alot. I have the following case 
1. Load the map with no sql source
2. Search for an address, retrieve the Lat/Lng.
3. Go to the that positition.
a marker is created on that position, this marker is not draggable. I noticed that if the marker was drawn with an ID (from SQL source), the marker will be draggable. Is this how the plugin behaves of it is a bug?
Omar

**Comment by jeffreykemp** [comment]
If the user places a pin, or the map places a pin based on an address search, set the pin as Draggable if the plugin's Draggable option is set.

**Comment by omarsawalhah** [comment]
@jeffreykemp How to implement this update, should we clone the repo, or there is a new release coming? 
Omar

**Comment by jeffreykemp** [comment]
Hi Omar,

This has been fixed in Release 1.3. I'll get this finished and released as soon as possible, hopefully this week.

Jeff

**Comment by jeffreykemp** [comment]
v1.3
