### ISSUE TITLE
Error while page load 

### ISSUE THREAD

**Issue by mahmoudyo84** [jeffreykemp/jk64-plugin-reportmap#131]
hi
thanks for your plugin , but i am facing error while page loaded 'This page can't load Google Maps correctly.' and map has watermark 'For developer only' , i am config google map api correctly but still facing error , your advice appreciated 

thanks

**Comment by jeffreykemp** [comment]
Please post any errors or warnings in the browser console.

**Comment by hossamassadallah** [comment]
hi 
i have err in the console 
thank you for using the jk64 Report Map plugin!To access the Google Map object on this page, use:$("#map_map_testmap").reportmap("instance").map   More 
info: https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki

**Comment by hossamassadallah** [comment]
after set this code i have err  Uncaught TypeError: Cannot read property 'map' of undefined

**Comment by jeffreykemp** [comment]
That message means that the plugin code has loaded correctly, but if you're still getting the "This page can't load Google Maps correctly." error that means something else is wrong, possibly with your Google Maps API key. Please post the entire log from your browser console.

**Comment by jeffreykemp** [comment]
Closing as presumed fixed - please comment if further issues encountered.
