### ISSUE TITLE
Suppress "No Data Found" message

### ISSUE THREAD

**Issue by RichardAPickett** [jeffreykemp/jk64-plugin-reportmap#132]
Jeff, thank you for developing this plugin, I'm finding it very helpful and it is saving me lots of time on a current project. My question is whether it is possible to stop the _No Data Found_ message from appearing? For example, "No Data Found" could be the default message in the _When No Data Found_ box in the attributes, so that if it was cleared no message would be displayed. Currently, if the box is cleared you still get the default message. In my case, because there is also a synchronised report, it is obvious when there is no data.

**Comment by jeffreykemp** [comment]
Interesting idea.

Currently the plugin always shows "No Data Found" if the source query returns 0 rows; the normal expectation is that if it has a source query that "no rows found" indicates a potential problem (e.g. the user's search result was empty). As you say, it is common to have a report shown on the same page with the search results, so we don't necessarily need a big "No Data Found" message to appear on the map as well.

Enhancement: don't show the "No Data Found" message, unless the developer has explicitly specified this message in the **When No Data Found** region attribute.

**Comment by jeffreykemp** [comment]
APEX supplies a default "No Data Found" message if none is specified, so I'll implement this feature using a new option - "Suppress No Data Found message", default is No (preserve past behaviour)
