### ISSUE TITLE
I can't display info on the marker

### ISSUE THREAD

**Issue by jcarlos314** [jeffreykemp/jk64-plugin-reportmap#137]
Hello, awesome plugin. I have an issue with the markers, it doesn't show up the information when I click on them. Here's how I declared in the plugin:

```
SELECT LATITUDE as lat,
       LONGITUDE as lng,
       CUSTOMER_NAMES as name,
       ORDER_ID as id
FROM VYR_ORDERS_VIEW
```
![image](https://user-images.githubusercontent.com/57166132/98581559-85ba5a80-2276-11eb-921b-91962f3612c8.png)
![image](https://user-images.githubusercontent.com/57166132/98581510-720ef400-2276-11eb-8449-41ac75d4d88b.png)

**Comment by jeffreykemp** [comment]
Your query doesn't provide any info to show in the popup - you need a 5th column in your query.

https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/SQL-Query-Examples
