### ISSUE TITLE
LIVE GPS Tracking!

### ISSUE THREAD

**Issue by fahadrafique** [jeffreykemp/jk64-plugin-reportmap#138]
Thanks for the amazing work.
Do you offer live GPS tracking (like an UBER etc.)? if yes, kindly refer any example.

**Comment by jeffreykemp** [comment]
I'm not sure this is in the scope of this plugin. The plugin simply shows a map, and shows whatever data you wish to show on it. Where your application gets its data, or what it does with the user's current location, is the responsibility of the app.

For example, if the vehicle you are tracking reports its location regularly to your server, you can have the map periodically re-query the server for the latest position of the vehicle and move a pin accordingly.
