### ISSUE TITLE
Missing Marker Cluster Icons

### ISSUE THREAD

**Issue by simongadd** [jeffreykemp/jk64-plugin-reportmap#142]
**Describe the bug**
Using Marker Clusters but the cluster icons are not rendering (see screenshot)

**Expected behaviour**
When multiple points are passed to the Map region, clusters should display. At the moment it appears the javascript is unable to reference the required icons.

**Screenshots**
![Screenshot 2021-01-18 at 10 21 26](https://user-images.githubusercontent.com/26631574/104902739-fe285080-5976-11eb-9132-5b0f636a2fb4.png)

**Additional context**
Running on an Oracle Cloud Hosted APEX instance - not sure if that would affect the behaviour.
Have trawled through StackOverflow etc but don't see any pointers to resolving the issue.

**Comment by jeffreykemp** [comment]
Thanks, can you check the browser console - on the Network tab you should see the failing requests - check what URL it's attempting to download the icons from.

The plugin has some code that tries to parse the URL for friendly or legacy URLs and it's possible there's something different about the URLs on the hosted instances.

**Comment by simongadd** [comment]
Hi Jeffrey

Yes, the Network tab is highlighting that it can’t find the resource(s) here…

https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/r/hms_fire/109/files/plugin/205655411308243901/v638/images/m1.png <https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/r/hms_fire/109/files/plugin/205655411308243901/v638/images/m1.png>

Can I modify the code to pull them from the Application Static Files?

BR
S

**Comment by jeffreykemp** [comment]
Editing the plugin to use application static files will probably encounter the same issue.

Can you post what the URL is for the page?

Also, run the page in APEX debug mode and check the debug log for these lines (search for "_getWindowPath" and post them here, e.g.:

```
reportmap._getWindowPath
debug.js?v=20.2.0.00.20:258 Friendly URL detected https://apex.oracle.com/pls/apex/jk64/r/jk64_report_map61081/clustering
debug.js?v=20.2.0.00.20:258 path https://apex.oracle.com/pls/apex
debug.js?v=20.2.0.00.20:258 imagePrefix https://apex.oracle.com/pls/apex/jk64/r/61081/files/plugin/32974076922090713201/v637/images/m
```

**Comment by jeffreykemp** [comment]
Another thing that might help me, if you could check the Network tab for the URL of the resource `jk64reportmap_r1.js`, e.g.

    https://apex.oracle.com/pls/apex/jk64/r/61081/files/plugin/33976076922090712201/v637/jk64reportmap_r1.js

**Comment by simongadd** [comment]
Hi Jeffrey

Thanks very much for taking a look at this. I know were into your evening and you’re doing this out of the goodness of your heart. :-)

The page is here… 
https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/ords/r/hms_fire/mælaborðinu/brunavarnaráætlanir?session=115639254077923 <https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/ords/r/hms_fire/m%C3%A6labor%C3%B0inu/brunavarnar%C3%A1%C3%A6tlanir?session=115639254077923>

Could the ‘friendly’ URL be causing the issue?

Not seeing anything here…
SELECT * FROM APEX_DEBUG_MESSAGES
where message like '%WindowPath%'
order by ID desc

**Comment by simongadd** [comment]
Hi Jeffrey

It’s https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/ords/r/hms_fire/109/files/plugin/205655411308243901/v638/jk64reportmap_r1.js <https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/ords/r/hms_fire/109/files/plugin/205655411308243901/v638/jk64reportmap_r1.js>

**Comment by jeffreykemp** [comment]
No problem.

The WIndowPath debug logs should be visible in the browser Console Log (not in APEX) but only when APEX debug mode is on.

**Comment by jeffreykemp** [comment]
Regardless, I think I can see what's going wrong anyway. I'll investigate further and hopefully get a fix together shortly.

**Comment by jeffreykemp** [comment]
Hi Simon,

I've made a small adjustment to try to take care of this issue. I'm not sure if it's absolutely correct for all cases (I'll have to find out more about how URLs work on the hosted cloud instance) but in your case I think this might work for now:

To try it, please download the plugin from here: [https://github.com/jeffreykemp/jk64-plugin-reportmap/blob/Patch-1-4-2/region_type_plugin_com_jk64_report_google_map_r1.sql](https://github.com/jeffreykemp/jk64-plugin-reportmap/blob/Patch-1-4-2/region_type_plugin_com_jk64_report_google_map_r1.sql) install it in your instance and see if it takes care of the issue.

If the issue persists, please check the debug logs again (as before) and post the results.

Thanks again

**Comment by simongadd** [comment]
Got it

[Log] reportmap._getWindowPath (desktop_all.min.js, line 5)
[Log] Friendly URL detected – "https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/ords/r/hms_fire/m%C3%A6labor%C3%B0inu/brunavarnar%C3%A1%C3%A6tlanir" (desktop_all.min.js, line 5)
[Log] path – "https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com" (desktop_all.min.js, line 5)
[Log] imagePrefix – "https://tcqqxwk4o7udq5x-hgrdevatp.adb.eu-frankfurt-1.oraclecloudapps.com/r/hms_fire/109/files/plugin/205655411308243901/v638/images/m" (desktop_all.min.js, line 5)

**Comment by jeffreykemp** [comment]
Sorry, I was expecting to see "Friendly URL detected (hosted cloud)" - not sure if it's a problem on your side or mine. Are you sure you imported the plugin? e.g. go into Shared Components / Plugins and check that the version is 1.4.2.

**Comment by simongadd** [comment]
Hi Jeffrey - Version is 1.4 

I am yet to use the v1.4.2 patch

Will keep you posted - most likely tomorrow (your time)

BR

Simon

**Comment by simongadd** [comment]
Bingo Jeffrey

V1.4.2 is working perfectly!

Many thanks

S

**Comment by jeffreykemp** [comment]
Thanks!

**Comment by jeffreykemp** [comment]
In release 1.5, a new optional application-level attribute has been added that will make this configurable (in case in future there is a new service with a URL structure my auto-detect code cannot handle).
