### ISSUE TITLE
Is the database Oracle XE v 11gR2 Supported?

### ISSUE THREAD

**Issue by GasparYYC** [jeffreykemp/jk64-plugin-reportmap#143]
Hi @jeffreykemp 
Awesome project, I can't wait to get started but I have Oracle 11g XE R2 and while installing the supporting objects I got the following error when I tried to install demo_app_182.sql R1.5:

*jk64demo_objects.sql*

```
create table jk64demo_countries
( country varchar2(255) not null
, iso_a2 varchar2(2)
, iso_a3 varchar2(3)
, lat number
, lng number
, geometry clob
, constraint country_name_uk unique (country)
, constraint iso_a2_uk unique (iso_a2)
, constraint iso_a3_uk unique (iso_a3)
, constraint geometry_is_json check (geometry is json)
)

ORA-00908: missing NULL keyword
```

When I remove the last line "constraint geometry_is_json check (geometry is json)" then the table creation works fine.

I looked at the requirements and did not find anything about the database so I'm asking for information.

If possible could you please confirm if 11gR2 is supported or no?

Thank you
Gaspar

**Comment by jeffreykemp** [comment]
The plugin is supported on 11gR2 but the demo app might encounter some issues like this.

Most of the demo will work without this particular table so you can skip it if you like, or remove the following line:

    , constraint geometry_is_json check (geometry is json)
