### ISSUE TITLE
Enable Marker Clustering for Oracle Apex

### ISSUE THREAD

**Issue by VictorZhuMBA** [jeffreykemp/jk64-plugin-reportmap#147]
Hi Jeff,

May I ask if the marker clustering function is automatic on Oracle Apex? I have a dataset covered with markers but the clustering function is not there. I could not find an option in Attributes to enable marker clustering either. 

Thank you!
![Capture](https://user-images.githubusercontent.com/72365989/106368017-194a7700-630c-11eb-8938-816ec162327c.PNG)

**Comment by jeffreykemp** [comment]
Yes, set the Visualisation to Marker Clustering.

https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Plugin-Attributes-Reference#visualisation
