### ISSUE TITLE
"GET" Value of clicked marker

### ISSUE THREAD

**Issue by simongadd** [jeffreykemp/jk64-plugin-reportmap#150]
Hi Jeff

May I ask, is there a simple way to 'get' the value of a 'clicked' marker?

I can create the Dynamic Action based on the 'markerClick' event but I'm not sure about the syntax I should use to get the value of the 'id' of the selected marker.

I want to set an APEX item value to the value of the marker and then refresh a report.

Any input for a javascript novice would be most appreciated.

Many thanks

Kind regards

Simon

**Comment by jeffreykemp** [comment]
Refer to: https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Plugin-Events-Reference#markerclick

In your trigger action you can refer to `this.data.id`.

**Comment by simongadd** [comment]
Perfect - Many thanks Jeff
