### ISSUE TITLE
Combine GeoJSON with Marker Clustering

### ISSUE THREAD

**Issue by simongadd** [jeffreykemp/jk64-plugin-reportmap#151]
Hi Jeffrey

Is it possible to combine two visualisations? In my Use Case, I'd like to see different jurisdictions as well as the pin clusters.

Many thanks

Simon

**Comment by jeffreykemp** [comment]
Only one visualisation can be chosen, but with some JavaScript you can add additional layers to the map after page load.

In your scenario, I would show the pins using the Clustering visualisation, and then after page load call the loadGeoJsonString API https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Plugin-API-Reference#loadgeojsonstring to show the additional layer.
