### ISSUE TITLE
Error JSON.parse 

### ISSUE THREAD

**Issue by sebastian-diedrich** [jeffreykemp/jk64-plugin-reportmap#152]
<img width="1526" alt="Bildschirmfoto 2021-10-25 um 14 19 31" src="https://user-images.githubusercontent.com/58628529/138693883-b120a87f-2e8d-4695-97a7-9f0de509efd7.png">

Hi!

Selecting a simple table with lng, lat, name, id produced the above error. Same problem with dual select (select * from dual). 

Any idea whats wrong? Got this JSON error.

BR
Sebastian

**Comment by jeffreykemp** [comment]
It looks like your Google Maps API key perhaps isn't correctly set?
