### ISSUE TITLE
Different colors of pin depending on the type of data

### ISSUE THREAD

**Issue by darkojic** [jeffreykemp/jk64-plugin-reportmap#156]
Is there any way to get some kind of enhancement like - to have different colors of pins, which are depending of some kind of parameter. E.g. there are locations of types 1, 2, 3...

For locations of type 1, the pin would be red,
For locations of type 2, the pin would be blue..
...type 3... yellow, type 4 gray... etc.  or even a different pin shape...

I am using this plugin and it's really effective and easy to use. I tried Apex Map Region and it's not even near as good as your plugin. At least there is no Google Maps coverage.

Thanks.

**Comment by jeffreykemp** [comment]
You can do this with a custom marker format function.
Refer to https://apex.oraclecorp.com/pls/apex/f?p=46203:25 for a demo and samples.
