### ISSUE TITLE
how can i join two tables and display markers of both table? not a single query seems to work!! HELP

### ISSUE THREAD

**Issue by AnushaGahukar** [jeffreykemp/jk64-plugin-reportmap#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

If your request is to add support for a particular [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/reference/) feature, if you can provide a link to the specific API documentation for the feature here it would be appreciated.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've tried or considered.

**Additional context**

**Comment by jeffreykemp** [comment]
What have you tried so far? Please provide details.

**Comment by AnushaGahukar** [comment]
Thank youu,  thats done!! can you give me hint about how to show and disappear markers while we zoom our map in and out??

**Comment by jeffreykemp** [comment]
By default the map will show all markers that are within the viewing area.
If there are too many markers to show, you might consider using one of the alternative visualisations, such as Spiderfier.
