### ISSUE TITLE
set zoom out level on page load for map region

### ISSUE THREAD

**Issue by raghu607** [jeffreykemp/jk64-plugin-reportmap#161]
Hi Jeff,

How can we set zoom out level when the page loads for the map region?

Thanks,
Ragu

**Comment by raghu607** [comment]
Hey Jeff,

Thank you, I added a dynamic action to set the zoom (this.data.map.setZoom(15);) for map loaded action but however in chrome when the apex map region loads I keep getting an process (spinning) icon and when I look at inspect element for any errors; I see the below error; any idea what might be causing this issue. 

Uncaught TypeError: Cannot read properties of undefined (reading 'getSouthWest')
    at kj.<anonymous> (jk64reportmap_r1.js:1229:40)
    at _.O (js?key=AIzaSyevsgkvwLRCk4OzQsqq3r3TqgsY3pIx4:97:320)
    at Hf (js?key=AIzaSyevsgkvwLRCk4OzQsqq3r3TqgsY3pIx4:99:320)
    at _.P.set (js?key=AIzaSyevsgkvwLRCk4OzQsqq3r3TqgsY3pIx4:267:758)
    at kj.setZoom (js?key=AIzaSyevsgkvwLRCk4OzQsqq3r3TqgsY3pIx4:107:279)
    at Object.javascriptFunction

**Comment by jeffreykemp** [comment]
Thanks for reporting this. I'll get a fix made ASAP.

**Comment by jeffreykemp** [comment]
Thanks for reporting this.

If you put an action on the Page Load event, it is expected to fail because the map region will not have been loaded yet.

Instead, you can set the Initial Zoom attribute directly on the map region.

If the map has data (i.e. a query data source), you can use the **mapLoaded** event instead of Page Load to use your dynamic action.

**Comment by raghu607** [comment]
Hi Jeff,  I am using map loaded event in the dynamic action not using any page load event. Not sure what's causing this issue in chrome browser.

Thanks,
Ragu

**Comment by jeffreykemp** [comment]
I was able to reproduce the error when using the Page Load event, but not when using the mapLoaded event, sorry.

Can you build an example on apex.oracle.com? I would be happy to take a look if you can reproduce the problem there.
