### ISSUE TITLE
Images on Map 

### ISSUE THREAD

**Issue by knkaran23** [jeffreykemp/jk64-plugin-reportmap#163]
How to show Images on pin point of Map in this plugin ?

**Comment by jeffreykemp** [comment]
The icon (image) to show instead of a pin is the optional 6th column of the query - 

SELECT lat, lng, name, id, info, icon FROM mydata;

"icon" needs to be a string which is the full URL path to the image to use. Note that the image must be publicly accessible.

**Comment by jeffreykemp** [comment]
Example: https://apex.oracle.com/pls/apex/r/jk64/jk64_report_map/icons
