### ISSUE TITLE
Geojson - marker improvements

### ISSUE THREAD

**Issue by josefn10** [jeffreykemp/jk64-plugin-reportmap#164]
Is possible create marker with info window from Geojson and register click or drag event for selecting marker with javascript $("#map_mymap").reportmap("click","#ID#")?

**Comment by patty1997** [comment]
Whenever I try this it gives a JS error. 

Uncaught Error: cannot call methods on reportmap prior to initialization; attempted to call method 'click'
    at Function.error (desktop_all.min.js?v=23.1.0:2:2616)
    at HTMLDivElement.<anonymous> (desktop_all.min.js?v=23.1.0:31:3977)
    at Function.each (desktop_all.min.js?v=23.1.0:2:3003)
    at S.fn.init.each (desktop_all.min.js?v=23.1.0:2:1481)
    at q.fn.<computed> [as reportmap] (desktop_all.min.js?v=23.1.0:31:3716)
    at <anonymous>:1:13
  
I have tried this on apex.oracle.com as well as on my instance. 

Could you help where am I going wrong?

I followed the exact configuration given in your app.

**Comment by jeffreykemp** [comment]
You can't call map methods until after the map is loaded. You can do this from a dynamic action on one of the following trigger events:
* mapLoaded - if your map has data (a SQL query)
* mapIdle - if your map has no data

**Comment by patty1997** [comment]
But then how can I sync my report with the map in this case? 
Let's say I created a report and it's column ciickable. What should the link be? 

Or Let's say I create a dynamic action that triggers when the map is loaded. 
How can I sync my report then?

Before that thank you for your help till now. Highly appreciated.

**Comment by patty1997** [comment]
> But then how can I sync my report with the map in this case? Let's say I created a report and it's column ciickable. What should the link be?
> 
> Or Let's say I create a dynamic action that triggers when the map is loaded. How can I sync my report then?
> 
> Before that thank you for your help till now. Highly appreciated.

Hey, It worked. Sorry. The link to the column was supposed to have 'map_' as a prefix. I didn't observe it carefully, 

Great PLugin my friend! Thanks!
