### ISSUE TITLE
Clustering Pins images not found

### ISSUE THREAD

**Issue by patty1997** [jeffreykemp/jk64-plugin-reportmap#166]
**Describe the bug**
The yellow and blue clustering pins fails to load.

Error :  GET https://apex.oracle.com/pls/r/abc/222849/files/plugin/26052700989957871660/v870/images/m1.png 404

**To Reproduce**
1. Go to 'attributes'
2. Select on 'Clustering marking'

**Comment by jeffreykemp** [comment]
Thanks - looks like possibly a problem on apex.oracle.com. I've reproduced the problem on my workspace there.
It works fine on our internal APEX instance, so I don't think this is necessarily a bug with the plugin.
I'll see what else I can find out.

**Comment by patty1997** [comment]
Oh Okay Thanks!
