### ISSUE TITLE
Use jQuery Widget Factory

### ISSUE THREAD

**Issue by martindsouza** [jeffreykemp/jk64-plugin-reportmap#17]
Instead of having functions and global variables that are unique to each instance of this plugin it may be better to have one JS package of code to handle everything. Thankfully there's a great framework to do this call the [jQuery Widget Factory](https://jqueryui.com/widget/) It's what all the jQuery UI widgets are built on.

If you've never used it before it can be a bit intimidating. [This site ](https://learn.jquery.com/jquery-ui/widget-factory/how-to-use-the-widget-factory/) should help get you started.

**Comment by jeffreykemp** [comment]
I do intend to look into using the widget factory, looks doable. In the meantime I've reduced the footprint a great deal by refactoring almost all the javascript out to a single js file loaded once per page.

**Comment by jeffreykemp** [comment]
This has been done in v1.0. The plugin now supports a range of API calls as well.
