### ISSUE TITLE
apex23 #PLUGIN_FILES#images/*.png not working

### ISSUE THREAD

**Issue by Mgosoriok** [jeffreykemp/jk64-plugin-reportmap#171]
**Describe the bug**
The application is unable to find #PLUGIN_FILES#images/*.png , explorer is reporting 404 error.

**To Reproduce**
Steps to reproduce the behavior: Try to display any page that contains "Clustering" Info

**Expected behavior**
Application Should display the plugin images

**Screenshots**
[Error](https://idbeg8s60nwh.objectstorage.us-ashburn-1.oci.customer-oci.com/n/idbeg8s60nwh/b/atmz_public/o/socialmedia%2FCaptura%20de%20pantalla%202023-12-12%20a%20la(s)%2011.26.55.png)

**Device (please complete the following information):**
 - Plugin Version : JK64 Report Google Map R1 (1.3.1)
 - APEX Version : 23.1.5
 - Oracle Database Version : 19c
 - Browser : chrome 120.0.1 (64-bit)
 - OS: OSx 14.1.2 (23B92)
 - Type: Desktop

**Plugin Attributes**

https://xxxx.adb.us-ashburn-1.oraclecloudapps.com/r/portal/555/files/plugin/212259628532432307/v588/images/m3.png
[HTTP/1.1 404 Not Found 174ms]
GET
https://xxxx.adb.us-ashburn-1.oraclecloudapps.com/r/portal/555/files/plugin/212259628532432307/v588/images/m2.png
[HTTP/1.1 404 Not Found 174ms]
GET
https://xxxx.adb.us-ashburn-1.oraclecloudapps.com/r/portal/555/files/plugin/212259628532432307/v588/images/m1.png
[HTTP/1.1 404 Not Found 375ms]

**Comment by Mgosoriok** [comment]
Hi Jeyffrey, just share with you the libraries are properly referenced , but the images path it is being not properly "built". Any clue ?  I checked the plugin code.. but I dont want to change before report to you. thanks.!!!

**Comment by Mgosoriok** [comment]
![Captura de pantalla 2023-12-12 a la(s) 11 59 19](https://github.com/jeffreykemp/jk64-plugin-reportmap/assets/6697450/e83c6534-e532-4ccf-8ce9-8a06a78fccde)

Important to mention all files are correctly uploaded

**Comment by jeffreykemp** [comment]
Thanks for reporting this, I can see the same issue in the demo app. Looks like regression after APEX 23.1.

**Comment by jeffreykemp** [comment]
A workaround in the meantime would be to copy these 5 images (m1.png, m2.png, m3.png, m4.png, m5.png) into the Application Images in the app, then set the plugin region **JavaScript Initialization Code** to: 
`
this.options.iconBasePath = '#APP_IMAGES#';
`
(as described here: https://apex.oracle.com/pls/apex/r/jk64/jk64_report_map/static)

**Comment by Mgosoriok** [comment]
Excelent! Thanks Jeffrey by your support! I will try the workaround and let you know ! Thanks!

**Comment by Mgosoriok** [comment]
Didnt worked... same issue...
![Captura de pantalla 2023-12-13 a la(s) 15 50 43](https://github.com/jeffreykemp/jk64-plugin-reportmap/assets/6697450/beb170ab-8480-49ef-92b1-72f2d5668d7d)

**Comment by Mgosoriok** [comment]
Didnt work!!! 

.......this.options.iconBasePath = '#APP_IMAGES#';

**Comment by jeffreykemp** [comment]
Did you copy the images to your Static Application Files? Check the URL paths to them.

**Comment by jeffreykemp** [comment]
This seems to apply to hosted instances where the URL no longer uses "/ords/r/" in the path, but "/apex/r/" now.
Fix to be included in release 1.6.

**Comment by giuseppe-bozzetti** [comment]
I do this but does't work

<img width="64" height="67" alt="Image" src="https://github.com/user-attachments/assets/9d576657-14bf-4ee5-af66-98d546e293a2" />


> A workaround in the meantime would be to copy these 5 images (m1.png, m2.png, m3.png, m4.png, m5.png) into the Application Images in the app, then set the plugin region **JavaScript Initialization Code** to: `this.options.iconBasePath = '#APP_IMAGES#';` (as described here: https://apex.oracle.com/pls/apex/r/jk64/jk64_report_map/static)

<img width="547" height="75" alt="Image" src="https://github.com/user-attachments/assets/c2e8ca90-5009-4ebc-b332-65400246f61a" />

<img width="321" height="142" alt="Image" src="https://github.com/user-attachments/assets/5dcb5e9a-627b-4fe6-af1a-de6636ba6942" />

**Comment by jeffreykemp** [comment]
If you're using the fixed version 1.6 you shouldn't need to apply the workaround.
