### ISSUE TITLE
Demo Report MAP is not working

### ISSUE THREAD

**Issue by machadcm** [jeffreykemp/jk64-plugin-reportmap#173]
Hi,

I'm getting the following error in all pages, except home page, of Demo Report MAP

![image](https://github.com/user-attachments/assets/1348b7f2-3330-4ead-b4ff-f4e408b1362e)

Thanks

**Comment by jeffreykemp** [comment]
Thanks for reporting - for some reason Friendly URLs had been disabled.

Fixed now
