### ISSUE TITLE
Possible by default satellite view 

### ISSUE THREAD

**Issue by waynelen6** [jeffreykemp/jk64-plugin-reportmap#30]
Hai, 

Is it possible by default satellite view?

Thanks
Regards
Wayne Len

**Comment by jeffreykemp** [comment]
Sorry for such a long delay responding to your question.

Yes, you can add a Dynamic Action to run some simple javascript to change the Map Type to Satellite view when the map is loaded.

Instructions: **[Tip - Show Satellite View on startup](/jeffreykemp/jk64-plugin-reportmap/wiki/Tip---Show-Satellite-View-on-startup)**
