### ISSUE TITLE
ORA-06502 "errore  di numero o valore" in non-English languages

### ISSUE THREAD

**Issue by glambardi** [jeffreykemp/jk64-plugin-reportmap#31]
Hi Jeff,
I would like to use your nice plugin; I tested in an apex 5.0.2 installation, and it appears to work very well if the application localization is English (en-us).
But, when I switch to an european one (es. IT - Italy), the apex region fails calling a number to char conversion error.
It probably has to do with decimal separator of lat and lng, but in the referenced table these values are stored in the correct form (dot separator, as downoloaded from google api web service)
Could you please suggest some fix for using this plugin when the application language isn't english?

Thank you very much for your help
Giulio

**Comment by jeffreykemp** [comment]
Hi, thanks for raising this issue. I believe I've fixed it - please download this release and try again:

https://github.com/jeffreykemp/jk64-plugin-reportmap/releases/tag/v0.7.1

If it still fails please let me know.
Jeff

**Comment by NuncaLoUsen** [comment]
Thanks Jeff,
For me the problem still persists.

Jairo

**Comment by jeffreykemp** [comment]
Hi Jairo,

I'm sorry to hear that. Would you be able to help me identify the source of the problem? I suspect I'm doing something wrong for non-English environments but not sure what it is.

Would you be able to create a workspace on apex.oracle.com and reproduce the problem? Please send me login credentials to the workspace so I can have a look.

Much appreciated,
Jeff

**Comment by NuncaLoUsen** [comment]
Hi Jeff,

I apologize, but the mistake was mine. In my data set (lat, lng) was too great precision.

This plugin is EXCELLENT and many thanks you for sharing it.

Regards,

Jairo

**Comment by jeffreykemp** [comment]
Hi Jairo,

Thanks very much for your kind words.

Even so, I can't see any good reason why the plugin should fail just because your data has too great precision - I'd rather have it capable of handling them.

I'll try to replicate myself, but would you be able to post some sample data that was failing previously?

Thanks heaps,

Jeff

**Comment by NuncaLoUsen** [comment]
Hi Jeff,

I received from a client, a table with lat and lng with type varchar2(30). 

**Sample data:**

lat old = 6.21461250000000000000, lat new = 6.21461250000000
lng old = -75.59815660000001000000, lng new = -75.59815660000001

With old data the error appeared, but with new data the error is not appearing.

In new data, I took only 14 decimals digits.

Just this corrected my problem.

With old data the error appeared, but with new data the error is not appearing.

Just this corrected my problem.

But, I repeat your plug-in is working very well. The error was mine.

**Comment by jeffreykemp** [comment]
If you're interested I've updated the plugin to support high-precision numbers - give it a try if you want.

Thanks again

**Comment by NuncaLoUsen** [comment]
Of course, I will watch this improvement and I will be reporting.

Thanks by your work.

Greetings,

Jairo
