### ISSUE TITLE
no map

### ISSUE THREAD

**Issue by pa794** [jeffreykemp/jk64-plugin-reportmap#32]
plugin does not show map.  i have installed version 0.7.2

what are required attributes for map to display?

**Comment by jeffreykemp** [comment]
Thank you for giving this plugin a try!

The minimum attributes is a query to run (e.g. select lat, lng, name, id from mytable) and a height (which is defaulted to 400).

I've updated the online demo to 0.7.2 and added a "Minimal Test" page and it seems to work for me:
[https://apex.oracle.com/pls/apex/f?p=15181:9](https://apex.oracle.com/pls/apex/f?p=15181:9)


Please check your browser's debug console for errors and if you can post a link to a demo online reproducing your problem I'd be happy to have a look.

Thanks, please keep me posted on your progress and let me know if I can help further.
Jeff

**Comment by jeffreykemp** [comment]
Closing - unable to reproduce
