### ISSUE TITLE
Render labels on pins

### ISSUE THREAD

**Issue by jeffreykemp** [jeffreykemp/jk64-plugin-reportmap#33]
As extra optional column in query

suggested by Lucas Hirschegger

**Comment by lucashir** [comment]
I have prepare the code, but reusing the ID as a label (while truncating it to 1 char). 
Did you think it is better to have a separate column for that?
Thanks

**Comment by jeffreykemp** [comment]
It will definitely be better as a separate column.

**Comment by lucashir** [comment]
Hi, 
I have adapted the code for a separate column. Funny is, that works only when debug mode, otherwise the marker is not created. On my first manual implementation happens, that the map was rendered before the markers were created. I solved it executing the fitBounds after the Markers... 
Any idea here?

**Comment by lucashir** [comment]
It works now, typo on the min js file. Seems like I cannot push the changes to a new branch. Should I 
send it to you directly?

**Comment by jeffreykemp** [comment]
if you like

*Jeffrey Kemp*
Phone: 0408 288 568
Email: jeffrey.kemp@jk64.com

**Comment by lucashir** [comment]
Here you have. Thanks!

[jk64-plugin-reportmap.zip](https://github.com/jeffreykemp/jk64-plugin-reportmap/files/611178/jk64-plugin-reportmap.zip)

**Comment by jeffreykemp** [comment]
Thanks Lucas. I have added your changes as v0.7.3 with a slight modification.

In order to not break existing code that may use the flex fields, we can't insert a new column at that point; instead, I've made the "label" a special usage of Flex Field 1. To enable flex field 1 as a label, you need to set the new plugin property "Attribute1" to "Label".

Also, to make the plugin easier to use I've modified the code to truncate the label to 1 character instead of raising an exception.

Please import the new version and let me know if it works ok for you.

Thanks again for your contribution.

**Comment by lucashir** [comment]
Sorry for the late reply. Can you please check if you commit the wrong version? I still see my -20001exception in the file. Thank you!

**Comment by jeffreykemp** [comment]
Sorry about that, I must have exported the wrong version. I've released 0.7.3 with the correct version I believe.
https://github.com/jeffreykemp/jk64-plugin-reportmap/releases/tag/v0.7.3
