### ISSUE TITLE
Lat Long decimal error

### ISSUE THREAD

**Issue by sanderbou** [jeffreykemp/jk64-plugin-reportmap#35]
Heyy Jeffrey,

First of all, thanks for the plugin! :)

I have tried your plugin, but when i put a decimal value in the lat or lng in the SQL statement, the plugin does not load any more (see the screenshots and the error in there below).
But, when i put a decimal value in the Initial Map Position, everything seems fine and the map loads without any problem. Am i doing something wrong? I hope you can help me out!

**Screenshot 1: table/column names + data**
![screenshot 1](https://cloud.githubusercontent.com/assets/19777147/20391844/745a8168-acd5-11e6-99bf-0887a2345263.png)
**Screenshot 2: the select statement in the plugin**
![screenshot 2](https://cloud.githubusercontent.com/assets/19777147/20391845/745a8be0-acd5-11e6-97c1-fab8e4aeead6.png)
**Screenshot 3: attribute settings part 1**
![screenshot 3](https://cloud.githubusercontent.com/assets/19777147/20392113/b0d59848-acd6-11e6-8cf1-7052f1990697.png)
**Screenshot 4: attribute settings part 2**
![screenshot 4](https://cloud.githubusercontent.com/assets/19777147/20391846/745b151a-acd5-11e6-82fd-773dff12c239.png)
**Screenshot 5: error in console**
![screenshot 5](https://cloud.githubusercontent.com/assets/19777147/20391843/745a5ae4-acd5-11e6-8f02-2d8a745b0b1b.png)

**Comment by jeffreykemp** [comment]
There was an earlier bug with certain numeric conversions. Please make sure you are using the latest release, 0.7.2.

I've tried creating a region with a query matching the data from your screenshot and it seems to work fine.

If you are already using this version and still getting this error, can you please set up a test case online, or perhaps send me an export of a minimal application with just the page with that region where it fails, and I will see if I can diagnose further.

Thanks!
![image](https://cloud.githubusercontent.com/assets/15881471/20394088/47754900-ad19-11e6-979f-a74f10df78da.png)

**Comment by sanderbou** [comment]
Hmm, i have the latest release installed.. but, i have some good news 👍 
In the first screenshots from the first post, i tried to make your plug-in work on a development environment from my school. But.. now i have tried it on the development environment from my work and everything seems to work fine!! 
So i think the problem is that i do not have all the rights on my development enviroment from my school (or something else..). 

Your plugin seems to be the perfect solution for the GEO map that i need in APEX, thank you for the development of the plug-in! :)

**Screenshot 6 the plug-in works fine :)**
![screenshot 6](https://cloud.githubusercontent.com/assets/19777147/20424250/23fe12e8-ad75-11e6-8d25-d3a8a23aee6f.png)

**Comment by jeffreykemp** [comment]
Thanks for that. It's possible there's another issue at play, perhaps a different NLS number format setting that the plugin isn't taking into account. I thought I'd taken care of all those issues but there might still be some residual bits. If you can reproduce the issue again let me know.

Thanks
