### ISSUE TITLE
On page load the default zoom is 0

### ISSUE THREAD

**Issue by msaron** [jeffreykemp/jk64-plugin-reportmap#38]
I have set the onclick zoom level to 15. On page load, the map defaults to a zoom level of 0. It is only after the user clicks on the map that it will zoom out to 15. How can I make it show a zoom level of 15 on map load? Thanks.

**Comment by jeffreykemp** [comment]
The Report Map plugin tries to set the default zoom based on the minimum and maximum latitudes and longitudes for the data to be reported. If there is no query to report, it *should* set the default zoom to 1. Otherwise, if the report returns no data I think it shows the maximum extent (zoom 0).
