### ISSUE TITLE
Make marker draggable

### ISSUE THREAD

**Issue by dickdral** [jeffreykemp/jk64-plugin-reportmap#40]
Hi Jeff, 

Thanks for creating this plug-in. I really like it. And it has got lots of functionality! I was on my way to create the same functionality when I discovered this one. 

One thing I needed was for markers to be draggable. I keep track of my expenses and use GPS to recognize which shop I am in. This is not always accurate, so I want to correct the positions afterward. 
I took your code and modified it a bit and got the draggable markers. I attach the modified plug-in (extension .txt instead of .sql) and a Word document describing the changes I have made.

Best wishes,

Dick Dral
[Changes to existing JK64 Google maps plugin to add draggable markers.docx](https://github.com/jeffreykemp/jk64-plugin-reportmap/files/1389966/Changes.to.existing.JK64.Google.maps.plugin.to.add.draggable.markers.docx)

[region_type_plugin_com_jk64_report_google_map28422.txt](https://github.com/jeffreykemp/jk64-plugin-reportmap/files/1389967/region_type_plugin_com_jk64_report_google_map28422.txt)

**Comment by jeffreykemp** [comment]
Thanks Dick, I'll certainly incorporate these changes.

**Comment by jeffreykemp** [comment]
Unfortunately the latest release has hit the limit of 25 attributes - will need to rework the plugin to allow this change.

**Comment by jeffreykemp** [comment]
This will be implemented in v1.0. The plugin will have an optional attribute "Draggable". If set, all the report pins will be draggable. When the user drags a pin, the plugin will raise a new event "markerDrag" which you can respond to using a dynamic action. You can then do whatever you want in response to the drag event.
