### ISSUE TITLE
Make automatic panTo feature controllable as a Region Setting attribute

### ISSUE THREAD

**Issue by orujokid** [jeffreykemp/jk64-plugin-reportmap#41]
The ReportMap pluginn is great, bit I would like to be able the switch on (or off) the automatic PanTo behavior when a marker is clicked.

For my application the PanTo movement of the map, "disturbs" and distracts the user to much from the marker-info I will display in a different section on the page.

**Comment by jeffreykemp** [comment]
v0.9 added Pan on click attribute
