### ISSUE TITLE
Add attributes to control zoom, pan, gesture handling

### ISSUE THREAD

**Issue by jeffreykemp** [jeffreykemp/jk64-plugin-reportmap#43]
* Zoom enabled (PL/SQL expression)
* Pan enabled (PL/SQL expression)
* Gesture Handling

**Comment by martenian** [comment]
Hey Jeff,

Is this the same enhancement that you added to the simple map? Does it include single finger panning for mobile devices?

Thanks again for providing this! I’ve learned a ton from your tutorials and code. Really appreciate it!

Thanks,

Mike

Mike

**Comment by jeffreykemp** [comment]
Hi Mike, yes this is the same idea.

**Comment by jeffreykemp** [comment]
v0.9 added new attributes
