### ISSUE TITLE
Geo Locate javascript

### ISSUE THREAD

**Issue by BizSafe** [jeffreykemp/jk64-plugin-reportmap#46]
Thank you for a fantastic plugin!

I'm having a difficult time trying to get the geo-locate feature working if I set it initially to No.  

I have set my static region id to mymap and created a radio button that has a dynamic action on change.  There I put the java script 

jk64plugin_geolocate(opt_mymap);
opt_mymap.map.setZoom(11);

But nothing seems to happen,

Any guidance will be sincerely appreciated

Thank you

**Comment by jeffreykemp** [comment]
Hi,

My apologies, there was a typo on my "Tip: Zoom to user's current location" page. The correct code has been updated. https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Tip:-Zoom-to-user's-current-location

The first javascript call should be to **jk64reportmap_geolocate**.

Thanks!

**Comment by BizSafe** [comment]
Thank you so much for the swift response, it is working now!  Is there a
way to save the cords into an item for the location once the map has
repositioned?

**Comment by jeffreykemp** [comment]
Yes, if you create a dynamic action on the map region that gets triggered by the geolocate event, you can then set the coords into an item with a Javascript action. The javascript action could be something like this:

`$s("P1_LATLONG", this.data.lat,lng+","+this.data.lng);`

https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Plugin-Attributes-Reference

**Comment by BizSafe** [comment]
Sincerely appreciated for your help.  Have a fabulous day further, I'm have
fun with your plugin!
