### ISSUE TITLE
2 Question.

### ISSUE THREAD

**Issue by JacoFourie** [jeffreykemp/jk64-plugin-reportmap#49]
1) Can you add a search item to enter a address to look for ?
2) Can you have a route and calculate the distance of the route ?

Thanks.

**Comment by jeffreykemp** [comment]
1. Yes, set the Geocode Item plugin attribute to the name of your search item.

2. Yes, use the Directions attributes.

Note: these both require you to set the Google API Key in your plugin Component Settings.

Refer to [Plugin Attributes Reference](https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Plugin-Attributes-Reference) for more information.

**Comment by JacoFourie** [comment]
Thank you . I will have a look.
