### ISSUE TITLE
2 tables... double ID's

### ISSUE THREAD

**Issue by BernhardFW** [jeffreykemp/jk64-plugin-reportmap#50]
Hi Jeff,
as recommended I use 2 tables with UNION ALL with different icons on the map.

Re: Sync report (left: map with icons of both tables - right: report of table 1)
when I click a name of table 1 in the report, using the ID the sync does work (most of the times...); 

BUT in both tables for some records by coincident I have the same value as ID and than the sync does not work... clicking on a record in the report of table 1 points to an icon/record of table 2...
How to solve ?
thanks
Bernhard

**Comment by jeffreykemp** [comment]
Modify your query to ensure the IDs are unique, e.g. by concatenating a different static value from each portion of the query, e.g.:

select 'A' || id as id, ... from tableA
union all
select 'B' || id as id, ... from tableB
