### ISSUE TITLE
Sorry. One more question.

### ISSUE THREAD

**Issue by JacoFourie** [jeffreykemp/jk64-plugin-reportmap#51]
Thanks for this cool plugins. I just want to understand how it works if I want a user to enter a route.
Will I have to use 2 regions. One to allow the user to select or find each of the way-point and add it to a table and the second region to show the full route ? Or can you do it all on one region ?

**Comment by jeffreykemp** [comment]
It depends on what the source of the waypoints is.

If you are using an interactive grid or tabular form to allow the user to enter/edit the waypoints in a table, this would need to be a separate region to the map region.

Otherwise, there is no strict requirement for a second region; however, you can use a separate region if you want more control over the UI layout.

**Comment by JacoFourie** [comment]
OK thanks.

I see this is the query that is used to find the route.

select c003 as lat, c004 as lng, c002 as name, c001 as id, c002 || ' (id=' || c001 || ')' as info
from apex_collections
where collection_name = 'ROUTE'
order by c001

If I use this query in TOAD I get no data back. Where is it getting the data from ?

I made my own table with same data types and changed the query to this

select lat ,  lng , name , row_id as id , row_id || ' (id=' || row_id || ')' as info
from jaco_route

Now I get this error.

````
Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -6502
ora_sqlerrm: ORA-06502: PL/SQL: numeric or value error
component.type: APEX_APPLICATION_PAGE_REGIONS
component.id: 130570715918024837
component.name: Report Google Map Plugin ("mymap")
````

**Comment by JacoFourie** [comment]
OK I found the problem. So no more error. Just where is your data coming from ?

**Comment by jeffreykemp** [comment]
APEX_COLLECTIONS is a view provided by APEX, and contains data created private to the current APEX session. If you query it from outside APEX (e.g. TOAD) it will not return any data.

https://docs.oracle.com/database/apex-18.1/AEAPI/APEX_COLLECTION.htm#AEAPI531

**Comment by JacoFourie** [comment]
Aaaa OK. Thanks a lot for the help. All is working now.
