### ISSUE TITLE
Support large datasets: only load pins for viewed area

### ISSUE THREAD

**Issue by jeffreykemp** [jeffreykemp/jk64-plugin-reportmap#52]
If the dataset is very large (e.g. >3000 pins), make it possible to only show up to a certain number (e.g. max 1000) pins loaded (e.g. via AJAX) based on the user's current viewport. i.e. when the user zooms in, or pans, it should reload the data but only for that area.

**Comment by darkojic** [comment]
Hello,
Is it possible to change this in way to group pins in circle, which will expand with zooming or something like that? There are some websites that use this way (e.g. circle with number of pins which are expanding on zoom).

I have this situation (see the picture). This is totally user unfriendly, and I need some way to resolve this.
![Mapa lokacija - Opera](https://user-images.githubusercontent.com/42218572/61044323-b1a2a300-a3d8-11e9-93ea-5091fd981814.jpg)

**Comment by jeffreykemp** [comment]
What might help here is to add support for Marker Clustering - https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by darkojic** [comment]
Yes, that is exactly what I had in my mind.

**Comment by jeffreykemp** [comment]
This will be implemented in v1.0.

**NOTE: I've upgraded to Oracle APEX 18.2 so the plugin will no longer support older versions.**

**Comment by darkojic** [comment]
> This will be implemented in v1.0.
> 
> **NOTE: I've upgraded to Oracle APEX 18.2 so the plugin will no longer support older versions.**

So, it wouldn't work in Oracle APEX 5.2? :/

**Comment by jeffreykemp** [comment]
Sorry, I don't have access to an APEX 5.2 instance anymore, unfortunately. If I was given access to one I would be happy to backport my changes to it, though.

**Comment by darkojic** [comment]
I would be glad to help if I can and know how.

**Comment by jeffreykemp** [comment]
I should have an opportunity to backport this to 5.0 within the next week or so.

**Comment by jeffreykemp** [comment]
Hi darkojic,

I have backported v1.0 to APEX 5.0.3. Can you please download it from the following URL and test it in your dev environment?

https://github.com/jeffreykemp/jk64-plugin-reportmap/blob/Patch-1-0-1/backport/region_type_plugin_com_jk64_report_google_map_r1_503.sql

Thanks very much.

**Comment by darkojic** [comment]
Hi, jeffreykemp.

I've just tried the new plugin, and it works like a charm. :)
![Mapa lokacija - Opera](https://user-images.githubusercontent.com/42218572/61625689-97d84a00-ac7b-11e9-98cd-e6f0870ce61e.jpg)

**Comment by jeffreykemp** [comment]
Excellent! Thanks for that.

**Comment by darkojic** [comment]
> Excellent! Thanks for that.

No problem. Thank you for plug-in update. :)

Great work!

**Comment by jeffreykemp** [comment]
Keep an eye out for the next release. The backport will be included and there will be some minor bugfixes that may or may not affect your use of it.
