### ISSUE TITLE
Changing

### ISSUE THREAD

**Issue by NuncaLoUsen** [jeffreykemp/jk64-plugin-reportmap#59]
Hi Jeffrey.

Is possible to change google icon marker by custom icon marker? I have my own set of icons and I want to use them instead of google.

Regards,

Jairo Cortés

**Comment by jeffreykemp** [comment]
Yes.

The query would require the 6th column (icon), the values of which must refer to an image file that will be used instead of the standard red pin.

If icons are supplied they need to be fully-qualified URIs to an icon image to be used. e.g.

    http://maps.google.com/mapfiles/ms/icons/blue-dot.png
