### ISSUE TITLE
markerClick event

### ISSUE THREAD

**Issue by BizSafe** [jeffreykemp/jk64-plugin-reportmap#60]
Hi Jeffery,
Firstly, thanks for your awesome plugin!!

I have a report that shows a bunch of markers.  I have set the 'Set Item Name to ID on Click' to my item :P1_SELECTED and can see the ID is set each time I click on a marker.  I am trying to get a dynamic action to redirect to a new page when :P1_SELECTED changes but that doesn't work so I thought the markerClick event might help and tried using a SetValue with this.data.id but I am not making any headway.

Any assistance would be greatly appreciated.  In short, I need each marker to be a link

Thank you
Sandy

**Comment by jeffreykemp** [comment]
Hi Sandy,

Thanks for trying the plugin. Typically the easiest way to do stuff like this is to put a dynamic action on change of the item P1_SELECTED; in your case I would have a dynamic action of "Submit" with a Request value (e.g. "GO"). You can then have a branch on your page which has a condition of "Request = GO" which redirects to the page you want.

I hope this helps.

Jeff

**Comment by BizSafe** [comment]
Thank you for the swift response Jeff, but I tried that and it doesn't
work.
These are the attributes I set for the plugin

[image: image.png]

I have an OnChange dynamic action set against P8_SELECTED, but the page
does not submit.
[image: image.png]

I also tried using the markerClick event but that didn't seem to work
either.  Could it be that other attributes are interfering?

Regards,
Sandy

**Comment by jeffreykemp** [comment]
I can't see your screen or your screenshots. Only way I can help you further is if you set up a test case on apex.oracle.com. Feel free to send me a link and login details to jeff@jk64.com.

**Comment by BizSafe** [comment]
Thanks Jeff, I'll do so and let you know when done

**Comment by BizSafe** [comment]
Hi Jeff,

I am seeing the following javascript error with the plugin on Chrome.

I suspect this is stopping the rest of my dynamic executions from
triggering.

Any ideas?

desktop_all.min.js?v=19.1.0.00.15:2 jQuery.Deferred exception: Cannot read
property 'lat' of undefined TypeError: Cannot read property 'lat' of
undefined
    at Object.attribute05 (
https://ouramazingrace.com/ords/f?p=111:8:14331481050679::NO::::303:510)
    at Object.a.setValue (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:22:1469
)
    at Object.da.doAction (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:5183
)
    at Object.da.doActions (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:3664
)
    at HTMLDivElement.<anonymous> (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:2597
)
    at Function.each (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2573
)
    at w.fn.init.each (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:1240
)
    at Object.da.actions (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:2315
)
    at Object.<anonymous> (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:21:975
)
    at Function.each (
https://ouramazingrace.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2573)
undefined
w.Deferred.exceptionHook @ desktop_all.min.js?v=19.1.0.00.15:2
desktop_all.min.js?v=19.1.0.00.15:2 Uncaught TypeError: Cannot read
property 'lat' of undefined
    at Object.attribute05 (f?p=111:8:14331481050679::NO::::303)
    at Object.a.setValue (desktop_all.min.js?v=19.1.0.00.15:22)
    at Object.da.doAction (desktop_all.min.js?v=19.1.0.00.15:21)
    at Object.da.doActions (desktop_all.min.js?v=19.1.0.00.15:21)
    at HTMLDivElement.<anonymous> (desktop_all.min.js?v=19.1.0.00.15:21)
    at Function.each (desktop_all.min.js?v=19.1.0.00.15:2)
    at w.fn.init.each (desktop_all.min.js?v=19.1.0.00.15:2)
    at Object.da.actions (desktop_all.min.js?v=19.1.0.00.15:21)
    at Object.<anonymous> (desktop_all.min.js?v=19.1.0.00.15:21)
    at Function.each (desktop_all.min.js?v=19.1.0.00.15:2)

Sandy

**Comment by jeffreykemp** [comment]
It looks like you've defined a dynamic action that does a Set Value. What is the expression you have used for your Set Value?

**Comment by BizSafe** [comment]
Hi,

I have a geolocate event that sets P8_MY_LAT to this.data.lat

Sandy

**Comment by jeffreykemp** [comment]
On the Action, have you set Fire on Initialization to **No**?

**Comment by BizSafe** [comment]
Hi, it's set to yes as I need to get the users location when they open the
page

**Comment by BizSafe** [comment]
you so clever ;o)

I set it off and everything is still working as intended.

Thank you
Sandy

**Comment by jeffreykemp** [comment]
I've encountered the same issue - it happens because when APEX runs the On Initialization steps, the map hasn't yet loaded. Later, when the map loads, depending on how things have been configured the geolocate event can fire and your dynamic action will then work.

Cheers

**Comment by jeffreykemp** [comment]
Thanks for raising this issue, I've added a note to the Wiki to help future readers.

**Comment by BizSafe** [comment]
Thanks again for the awesome plugin and for the great support.

Hope you have a brilliant day

Sandy
