### ISSUE TITLE
Spiderfiy Markers

### ISSUE THREAD

**Issue by SmileyMan** [jeffreykemp/jk64-plugin-reportmap#77]
Hi.

Even with marker cluster locations that have the exact same LAT/LNG hide each other (Converting Postcodes to LAT/LNG so happens to me)

I use
`
ROUND(LATITUDE + -0.00030 * COS((+90*dbms_random.value()) / 180 * 3.1415926), 10) AS LATITUDE
        ROUND(LONGITUDE + - 0.00030 * COS((+90*dbms_random.value()) / 180 * 3.1415926), 10) AS LONGITUDE
`
at the moment to move markers a little bit but found this does weird stuff to Marker Cluster (Duplicates markers)

_Cluster Markers that spiderfiy at around zoom 13-15 be excellent._

Some links to explain what I mean:

https://codepen.io/kimmenbert/pen/oxBrJK **_(Perfect)_**

https://jsfiddle.net/4mtyu/1833/

https://github.com/jawj/OverlappingMarkerSpiderfier

**Comment by jeffreykemp** [comment]
Added in Release 1.2
