### ISSUE TITLE
Drawing/Viewing of GeoJSON layers 

### ISSUE THREAD

**Issue by rsbudd** [jeffreykemp/jk64-plugin-reportmap#78]
Hello Mr. Kemp:

Is it possible to to draw (interactively), save to GeoJSON format the resulting polygon, and also to recall/reload/draw the GeoJSON upon the map with your jk64-plugin-reportmap?  I think I can utilize what is described for the Google API here with regards to layers; https://developers.google.com/maps/documentation/javascript/examples/layer-data-dragndrop  so that it performs similar to what we can visualize here: http://geojson.io   

The problem I'm trying to solve is to present a map to the end user, allow them to draw a geofence outline on the map (polygon, circles, square, etc.) and then save that in a standard GeoJSON format for later recall and post processing of vehicle gps breadcrumbs as they enter or exit the boundaries defined by the GeoJSON.  

Thank you -- big fan of your work and your continued writing, I learn quite a bit from the discussions.

Budd

**Comment by jeffreykemp** [comment]
Great idea. Not sure when I'll have time to dig into it myself but I'll keep this on the radar. In the meantime if you want to give it a shot I encourage you to do so.

**Comment by rsbudd** [comment]
> Great idea. Not sure when I'll have time

Completely understand ... would it be possible to pay you your normal consultancy rates to incorporate this feature?  My company has been using Apex since the 4.x days and have a number of projects across the US that are actively deployed (all in AWS thankfully), and there are times when "what we want to do" exceeds our "what we know how to do" threshold.  If not, no worries -- figured it couldn't hurt to ask.  Thank you for the response and consideration.

**Comment by jeffreykemp** [comment]
Email me at jeff@jk64.com to discuss.

**Comment by jeffreykemp** [comment]
* Add option to allow user to drag-and-drop GeoJSON fragments and files onto the map. The features are rendered on the map in the data layer.
* Event loadedGeoJson (for dynamic action).
* Add option to allow one or more shapes (marker, polygon, polyline, rectangle, and/or circle) to be added to the map by the user.
* Allow user to select a feature to move, edit, or delete it. Allow user to add extra polygons as "holes" in another polygon.
* Events: addFeature, removeFeature, setGeometry.
* Javascript API call to load GeoJSON string (e.g. from application code, or loaded from database).

**Comment by jeffreykemp** [comment]
Added in Release 1.1
