### ISSUE TITLE
not load js and css

### ISSUE THREAD

**Issue by droid2015** [jeffreykemp/jk64-plugin-reportmap#84]
**Describe the bug**
![image](https://user-images.githubusercontent.com/10129599/73808276-ec02e000-4801-11ea-8b8f-1b845f2ea7af.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Plugin Version [e.g. 1.0]
 - APEX Version [e.g. 18.2]
 - Oracle Database Version [e.g. 12.2]
 - OS: [e.g. iOS, Windows]
 - Type: [e.g. desktop, mobile phone]

**Plugin Attributes**
Run the page in Debug mode, copy the attributes from the console log here.

**Additional context**
Add any other context about the problem here, such as SQL query used, and sample data scripts.

**Comment by jeffreykemp** [comment]
The console log shows that key resources are not being loaded (note the 404 errors). There may be an issue in your environment.
