### ISSUE TITLE
Error: SyntaxError: Unexpected token { in JSON at position 1902

### ISSUE THREAD

**Issue by Blaxican** [jeffreykemp/jk64-plugin-reportmap#85]
**Describe the bug**
I have tested this plugin before, but for some reason on Oracle Cloud instance I am getting this erro: Error: SyntaxError: Unexpected token { in JSON at position 1902

**To Reproduce**
1. Bring up a ATP instance on Oracle Cloud
2. Install Plugin

**Expected behavior**
My view only has 5 data points for testing. None of them are loading and should have those few loading 

**Screenshots**

**Device (please complete the following information):**
 Everything latest and greatest and using Chrome on mac

**Comment by Blaxican** [comment]
Issue with column headers. Resolved on my own at this time

**Comment by Alien-nick** [comment]
@Blaxican Can you give a more indepth explanation? What do you mean by column headers? Is it the database columns you're talking about?
