### ISSUE TITLE
.reportmap("click") error in firefox

### ISSUE THREAD

**Issue by xCite1986** [jeffreykemp/jk64-plugin-reportmap#88]
with firefox i got following error with javascript click api function

![image](https://user-images.githubusercontent.com/10913090/76792436-588ada80-67c3-11ea-94b0-a58356b09407.png)

**Comment by jeffreykemp** [comment]
This is a known issue with some browsers (e.g. IE) with javascript calling jquery embedded in a href attribute (e.g. in the link attribute on a report column) and is not specific to this plugin.

The workaround is to wrap this in a function. In the page's Function and Global Declarations create a function like this:

````
function click_mymap (id) {
    $("#map_mymap").reportmap("click", id);
}
````

Change your report (or link) to:

````
javascript:click_mymap(id);
````

**Comment by jeffreykemp** [comment]
Documented https://github.com/jeffreykemp/jk64-plugin-reportmap/wiki/Issue:-some-browsers-show-%5Bobject-Object%5D-error-page
