### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by ScottMans** [jeffreykemp/jk64-plugin-reportmap#90]
Using your plug-in version 1.1 (backport install) in APEX 5.1.4.  Everything seems to be working fine in Chrome.  In IE I'm using the "sync with report" feature.  When I click the report link to zoom to the map marker I'm getting the following on a blank page.  

[object Object]

Clicking the markers directly works fine.  This issue also occurs on your APEX sample site with IE 11.

Please advise.

**Comment by xCite1986** [comment]
hey scott,

there is a workaround for that issue at https://github.com/jeffreykemp/jk64-plugin-reportmap/issues/88

alex

**Comment by ScottMans** [comment]
Excellent!!  Sorry for not finding that earlier.  I have applied the workaround and it seems to work in both IE and Chrome.  Thanks for pointing this out.
