### ISSUE TITLE
Map displays for less than 2 seconds

### ISSUE THREAD

**Issue by aminadatia** [jeffreykemp/jk64-plugin-reportmap#95]
**Describe the bug**
It may just be how I have defined the Page -- new to APEX and New to using the Map Plug in

I am using APEX v19.2
I have created a Page using the plugin
When I run the page  the positions display for about 2 seconds and then I get Sorry Something went wrong.

My query is

select
       VESSEL_REPORT_LAT     lat,
       VESSEL_REPORT_LON     lng,
       LOG_REPORT_DATE       name,
       trip_log_sk           id,
       LOG_TYPE_DESC
       ||'-'||ACTIVITY_AT_REPORT
       ||'- FISHING MINUTES => '||FISHING_MINUTES  info
  from EFMSI_TRIP_LOG_V
  where trip_log_sk not in (3500826,3500823,3500824)
  order by trip_log_sk

The Map I see for a few seconds is

![image](https://user-images.githubusercontent.com/60738767/80534997-1631ed00-896e-11ea-8c1e-95455c68f737.png)

**Device (please complete the following information):**
 - Plugin Version [e.g. 1.0]  1.1
 - APEX Version [e.g. 18.2] 19.2
 - Oracle Database Version [e.g. 12.2] 18c
 - Browser [e.g. chrome, safari] Chrome
 - OS: [e.g. iOS, Windows] Windows 10
 - Type: [e.g. desktop, mobile phone] desktop

**Plugin Attributes**
Run the page in Debug mode, copy the attributes from the console log here.

[19.docx](https://github.com/jeffreykemp/jk64-plugin-reportmap/files/4548396/19.docx)

**Additional context**
Add any other context about the problem here, such as SQL query used, and sample data scripts.

**Comment by jeffreykemp** [comment]
Please open the Console and look for any errors or warnings - this behaviour is often seen if the Google Maps API Key is wrong or missing.

**Comment by aminadatia** [comment]
Hi

Thanks.

It was the API settings. I was talking to Google support and they found the problem in my specifications. Working really well now.

For the clustering what setting do I have to use? and is it automatic or one or the other. Also is there a dynamic way to change the colour of the marker? I would like to have separate colour markers for when fishing is happening

Thanks for your API


Regards

Amin Adatia
613-864-8378

________________________________

**Comment by jeffreykemp** [comment]
To show icon clustering you set the Visualisation attribute to Marker Clustering.

To show markers with different colours, supply values for the "icon" (6th) column in your query:

    SELECT lat, lng, name, id, info, icon FROM mydata;

The icon must be a path to an icon file, which can be externally sourced or located in your application static files. For examples, refer to the demo pages:

https://apex.oracle.com/pls/apex/jk64/r/jk64_report_map/icons

https://apex.oracle.com/pls/apex/jk64/r/jk64_report_map/staticicons

More icons can be found here: http://kml4earth.appspot.com/icons.html

**Comment by aminadatia** [comment]
Hi

Thanks

So I can have all of my icons in a table and then select the BLOB at run time?

Also is it possible to switch between Pins and Marker Cluster. I noticed that zooming in on a cluster splits up the markers.



Regards

Amin Adatia
613-864-8378

________________________________

**Comment by jeffreykemp** [comment]
If your icons are in a BLOB, you would need to provide an application process that can be called from a URL to download them to the client. That is beyond the scope of this plugin.

The whole purpose of Marker Clustering is that when the pins are too close, they "cluster" automatically. When you zoom in, you don't need them clustered anymore and they automatically show up as separate pins.
