### ISSUE TITLE
Page Region type "JK64 Report Google Map R1 [Plug-In]" not available in drop down list

### ISSUE THREAD

**Issue by zhuchuanfu** [jeffreykemp/jk64-plugin-reportmap#98]
Hi Jeffrey,

Thanks for your demo.

I have Oracle APEX 19.02 and try to follow up https://jeffreykemp.github.io/jk64-plugin-reportmap/ to Leverage Google Maps. 
what could be wrong?

Thanks,

Frank Zhu

**Comment by jeffreykemp** [comment]
You need to install the plugin in your application.

1. Go to Shared Components
2. Open Plugins
3. Click Import
4. Select region_type_plugin_com_jk64_report_google_map_r1.sql

**Comment by zhuchuanfu** [comment]
Thanks Jeff,

You are best !

Frank Z.
    On Wednesday, April 29, 2020, 11:38:28 PM EDT, Jeffrey Kemp <notifications@github.com> wrote:  
 
 


You need to install the plugin in your application.
   
   - Go to Shared Components
   - Open Plugins
   - Click Import
   - Select region_type_plugin_com_jk64_report_google_map_r1.sql
